package:
    type:           yii2-extension
    name:           hidev-readme
    namespace:      hidev\readme
    headline:       HiDev README
    title:          README plugin for HiDev
    keywords:       readme, hidev, plugin
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin enables README generation support for HiDev.

        Provides README generation:
        - templates
        - sections
        - badges

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
